-- MySQL Script generated by MySQL Workbench
-- Sat Jan 11 23:23:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProdajaPrepisVozila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProdajaPrepisVozila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProdajaPrepisVozila` DEFAULT CHARACTER SET utf8 ;
USE `ProdajaPrepisVozila` ;

-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`MjestoStanovanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`MjestoStanovanja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grad` VARCHAR(20) NOT NULL,
  `opstina` VARCHAR(20) NOT NULL,
  `ulica` VARCHAR(20) NOT NULL,
  `broj` VARCHAR(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Lice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Lice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(20) NOT NULL,
  `prezime` VARCHAR(20) NOT NULL,
  `brojLicneKarte` VARCHAR(20) NOT NULL,
  `jmbg` VARCHAR(13) NULL,
  `MjestoStanovanja_id` INT NOT NULL,
  `TipLica` ENUM('PRAVNO', 'FIZICKO') NOT NULL,
  PRIMARY KEY (`id`, `MjestoStanovanja_id`),
  INDEX `fk_Lice_MjestoStanovanja1_idx` (`MjestoStanovanja_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lice_MjestoStanovanja`
    FOREIGN KEY (`MjestoStanovanja_id`)
    REFERENCES `ProdajaPrepisVozila`.`MjestoStanovanja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`VlasnikVozila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`VlasnikVozila` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Lice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Lice_id`),
  INDEX `fk_VlasnikVozila_Lice1_idx` (`Lice_id` ASC) VISIBLE,
  CONSTRAINT `fk_VlasnikVozila_Lice1`
    FOREIGN KEY (`Lice_id`)
    REFERENCES `ProdajaPrepisVozila`.`Lice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Vozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Vozilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `godiste` YEAR(4) NOT NULL,
  `registarskiBroj` VARCHAR(9) NULL,
  `brojSasije` VARCHAR(45) NULL,
  `brojMotora` VARCHAR(45) NULL,
  `VlasnikVozila_id` INT NOT NULL,
  PRIMARY KEY (`id`, `VlasnikVozila_id`),
  INDEX `fk_Vozilo_VlasnikVozila1_idx` (`VlasnikVozila_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vozilo_VlasnikVozila1`
    FOREIGN KEY (`VlasnikVozila_id`)
    REFERENCES `ProdajaPrepisVozila`.`VlasnikVozila` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`OstaloVozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`OstaloVozilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Vozilo_id`),
  INDEX `fk_OstaloVozilo_Vozilo1_idx` (`Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_OstaloVozilo_Vozilo1`
    FOREIGN KEY (`Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`Vozilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`PrikljucnoVozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`PrikljucnoVozilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `OstaloVozilo_id` INT NOT NULL,
  `OstaloVozilo_Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `OstaloVozilo_id`, `OstaloVozilo_Vozilo_id`),
  INDEX `fk_PrikljucnoVozilo_OstaloVozilo1_idx` (`OstaloVozilo_id` ASC, `OstaloVozilo_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_PrikljucnoVozilo_OstaloVozilo1`
    FOREIGN KEY (`OstaloVozilo_id` , `OstaloVozilo_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`OstaloVozilo` (`id` , `Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`PutnickoVozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`PutnickoVozilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Vozilo_id`),
  INDEX `fk_PutnickoVozilo_Vozilo1_idx` (`Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_PutnickoVozilo_Vozilo1`
    FOREIGN KEY (`Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`Vozilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`PutnickiAutomobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`PutnickiAutomobil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PutnickoVozilo_id` INT NOT NULL,
  `PutnickoVozilo_Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PutnickoVozilo_id`, `PutnickoVozilo_Vozilo_id`),
  INDEX `fk_Automobil_PutnickoVozilo1_idx` (`PutnickoVozilo_id` ASC, `PutnickoVozilo_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Automobil_PutnickoVozilo1`
    FOREIGN KEY (`PutnickoVozilo_id` , `PutnickoVozilo_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`PutnickoVozilo` (`id` , `Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`TeretnoVozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`TeretnoVozilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Vozilo_id`),
  CONSTRAINT `fk_TeretnoVozilo_Vozilo1`
    FOREIGN KEY (`Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`Vozilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Traktor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Traktor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TeretnoVozilo_id` INT NOT NULL,
  `TeretnoVozilo_Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TeretnoVozilo_id`, `TeretnoVozilo_Vozilo_id`),
  INDEX `fk_Traktor_TeretnoVozilo1_idx` (`TeretnoVozilo_id` ASC, `TeretnoVozilo_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Traktor_TeretnoVozilo1`
    FOREIGN KEY (`TeretnoVozilo_id` , `TeretnoVozilo_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`TeretnoVozilo` (`id` , `Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Motocikl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Motocikl` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PutnickoVozilo_id` INT NOT NULL,
  `PutnickoVozilo_Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PutnickoVozilo_id`, `PutnickoVozilo_Vozilo_id`),
  INDEX `fk_Motocikl_PutnickoVozilo1_idx` (`PutnickoVozilo_id` ASC, `PutnickoVozilo_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Motocikl_PutnickoVozilo1`
    FOREIGN KEY (`PutnickoVozilo_id` , `PutnickoVozilo_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`PutnickoVozilo` (`id` , `Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`KupacVozila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`KupacVozila` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Lice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Lice_id`),
  INDEX `fk_KupacVozila_Lice1_idx` (`Lice_id` ASC) VISIBLE,
  CONSTRAINT `fk_KupacVozila_Lice1`
    FOREIGN KEY (`Lice_id`)
    REFERENCES `ProdajaPrepisVozila`.`Lice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`KupoprodajniUgovor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`KupoprodajniUgovor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NULL,
  `cijenaVozila` INT NULL,
  `cijenaUgovora` INT NULL,
  `Vozilo_id` INT NOT NULL,
  `KupacVozila_id` INT NOT NULL,
  `VlasnikVozila_id` INT NOT NULL,
  `VlasnikVozila_Lice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Vozilo_id`, `KupacVozila_id`, `VlasnikVozila_id`, `VlasnikVozila_Lice_id`),
  INDEX `fk_KupoprodajniUgovor_Vozilo1_idx` (`Vozilo_id` ASC) VISIBLE,
  INDEX `fk_KupoprodajniUgovor_KupacVozila1_idx` (`KupacVozila_id` ASC) VISIBLE,
  INDEX `fk_KupoprodajniUgovor_VlasnikVozila1_idx` (`VlasnikVozila_id` ASC, `VlasnikVozila_Lice_id` ASC) VISIBLE,
  CONSTRAINT `fk_KupoprodajniUgovor_Vozilo1`
    FOREIGN KEY (`Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`Vozilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KupoprodajniUgovor_KupacVozila1`
    FOREIGN KEY (`KupacVozila_id`)
    REFERENCES `ProdajaPrepisVozila`.`KupacVozila` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KupoprodajniUgovor_VlasnikVozila1`
    FOREIGN KEY (`VlasnikVozila_id` , `VlasnikVozila_Lice_id`)
    REFERENCES `ProdajaPrepisVozila`.`VlasnikVozila` (`id` , `Lice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`KorisnickiNalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`KorisnickiNalog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `korisnickoIme` VARCHAR(20) NOT NULL,
  `lozinka` VARCHAR(20) NOT NULL,
  `prezime` VARCHAR(20) NOT NULL,
  `ime` VARCHAR(20) NOT NULL,
  `datumRodjenja` DATE NOT NULL,
  `jezik` ENUM('SRPSKI', 'ENGLESKI') NULL,
  `slikaProfila` LONGBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Administrator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `KorisnickiNalog_id` INT NOT NULL,
  PRIMARY KEY (`id`, `KorisnickiNalog_id`),
  INDEX `fk_Administrator_KorisnickiNalog1_idx` (`KorisnickiNalog_id` ASC) VISIBLE,
  CONSTRAINT `fk_Administrator_KorisnickiNalog1`
    FOREIGN KEY (`KorisnickiNalog_id`)
    REFERENCES `ProdajaPrepisVozila`.`KorisnickiNalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Sluzbenik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Sluzbenik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `KorisnickiNalog_id1` INT NOT NULL,
  `Administrator_id` INT NOT NULL,
  `Administrator_KorisnickiNalog_id` INT NOT NULL,
  PRIMARY KEY (`id`, `KorisnickiNalog_id1`, `Administrator_id`, `Administrator_KorisnickiNalog_id`),
  INDEX `fk_Sluzbenik_KorisnickiNalog2_idx` (`KorisnickiNalog_id1` ASC) VISIBLE,
  INDEX `fk_Sluzbenik_Administrator1_idx` (`Administrator_id` ASC, `Administrator_KorisnickiNalog_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sluzbenik_KorisnickiNalog2`
    FOREIGN KEY (`KorisnickiNalog_id1`)
    REFERENCES `ProdajaPrepisVozila`.`KorisnickiNalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sluzbenik_Administrator1`
    FOREIGN KEY (`Administrator_id` , `Administrator_KorisnickiNalog_id`)
    REFERENCES `ProdajaPrepisVozila`.`Administrator` (`id` , `KorisnickiNalog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`VoziloOdFirme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`VoziloOdFirme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vozilo_id` INT NOT NULL,
  `slika` LONGBLOB NOT NULL,
  `cijena` DOUBLE NOT NULL,
  `snizenje` DOUBLE NULL,
  `opis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Vozilo_id`),
  CONSTRAINT `fk_VoziloOdFirme_Vozilo1`
    FOREIGN KEY (`Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`Vozilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Ugovor_Sluzbenik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Ugovor_Sluzbenik` (
  `KupoprodajniUgovor_id` INT NOT NULL,
  `Sluzbenik_id` INT NOT NULL,
  `Sluzbenik_KorisnickiNalog_id1` INT NOT NULL,
  `datum_kreiranja` DATE NOT NULL,
  PRIMARY KEY (`KupoprodajniUgovor_id`, `Sluzbenik_id`, `Sluzbenik_KorisnickiNalog_id1`),
  INDEX `fk_Ugovor_Sluzbenik_Sluzbenik1_idx` (`Sluzbenik_id` ASC, `Sluzbenik_KorisnickiNalog_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Ugovor_Sluzbenik_KupoprodajniUgovor1`
    FOREIGN KEY (`KupoprodajniUgovor_id`)
    REFERENCES `ProdajaPrepisVozila`.`KupoprodajniUgovor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ugovor_Sluzbenik_Sluzbenik1`
    FOREIGN KEY (`Sluzbenik_id` , `Sluzbenik_KorisnickiNalog_id1`)
    REFERENCES `ProdajaPrepisVozila`.`Sluzbenik` (`id` , `KorisnickiNalog_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Korpa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Korpa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Racun` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Stavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Stavka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `KupoprodajniUgovor_id` INT NOT NULL,
  `VoziloOdFirme_Vozilo_id` INT NOT NULL,
  `cijena` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stavka_KupoprodajniUgovor1_idx` (`KupoprodajniUgovor_id` ASC) VISIBLE,
  INDEX `fk_Stavka_VoziloOdFirme1_idx` (`VoziloOdFirme_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stavka_KupoprodajniUgovor1`
    FOREIGN KEY (`KupoprodajniUgovor_id`)
    REFERENCES `ProdajaPrepisVozila`.`KupoprodajniUgovor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stavka_VoziloOdFirme1`
    FOREIGN KEY (`VoziloOdFirme_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`VoziloOdFirme` (`Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Korpa_Stavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Korpa_Stavka` (
  `Korpa_id` INT NOT NULL,
  `Stavka_id` INT NOT NULL,
  PRIMARY KEY (`Korpa_id`, `Stavka_id`),
  INDEX `fk_Korpa_has_Stavka_Stavka1_idx` (`Stavka_id` ASC) VISIBLE,
  INDEX `fk_Korpa_has_Stavka_Korpa1_idx` (`Korpa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Korpa_has_Stavka_Korpa1`
    FOREIGN KEY (`Korpa_id`)
    REFERENCES `ProdajaPrepisVozila`.`Korpa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korpa_has_Stavka_Stavka1`
    FOREIGN KEY (`Stavka_id`)
    REFERENCES `ProdajaPrepisVozila`.`Stavka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`Racun_Stavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`Racun_Stavka` (
  `Racun_id` INT NOT NULL,
  `Stavka_id` INT NOT NULL,
  PRIMARY KEY (`Racun_id`, `Stavka_id`),
  INDEX `fk_Racun_has_Stavka_Stavka1_idx` (`Stavka_id` ASC) VISIBLE,
  INDEX `fk_Racun_has_Stavka_Racun1_idx` (`Racun_id` ASC) VISIBLE,
  CONSTRAINT `fk_Racun_has_Stavka_Racun1`
    FOREIGN KEY (`Racun_id`)
    REFERENCES `ProdajaPrepisVozila`.`Racun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Racun_has_Stavka_Stavka1`
    FOREIGN KEY (`Stavka_id`)
    REFERENCES `ProdajaPrepisVozila`.`Stavka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProdajaPrepisVozila`.`TeretniAutomobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProdajaPrepisVozila`.`TeretniAutomobil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TeretnoVozilo_id` INT NOT NULL,
  `TeretnoVozilo_Vozilo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TeretnoVozilo_id`, `TeretnoVozilo_Vozilo_id`),
  INDEX `fk_TeretnoVozilo_TeretnoVozilo1_idx` (`TeretnoVozilo_id` ASC, `TeretnoVozilo_Vozilo_id` ASC) VISIBLE,
  CONSTRAINT `fk_TeretnoVozilo_TeretnoVozilo1`
    FOREIGN KEY (`TeretnoVozilo_id` , `TeretnoVozilo_Vozilo_id`)
    REFERENCES `ProdajaPrepisVozila`.`TeretnoVozilo` (`id` , `Vozilo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ProdajaPrepisVozila`;

DELIMITER $$
USE `ProdajaPrepisVozila`$$
CREATE DEFINER = CURRENT_USER TRIGGER `ProdajaPrepisVozila`.`Stavka_BEFORE_INSERT` BEFORE INSERT ON `Stavka` FOR EACH ROW
BEGIN
select cijena from ProdajaPrepisVozila.KupoprodajniUgovor as tabela
where id = NEW.KupoprodajniUgovor_id;
SET NEW.cijena = tabela.cijena;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
